CREATE TABLE reputation (
    kind        VARCHAR(8)    NOT NULL,
    lookup_key  VARCHAR(2100) NOT NULL,
    status      VARCHAR(16)   NOT NULL,
    detections  INTEGER       NOT NULL DEFAULT 0,
    engines     INTEGER       NOT NULL DEFAULT 0,
    label       VARCHAR(300),
    sources     VARCHAR(1000) NOT NULL DEFAULT '[]',
    fetched_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (kind, lookup_key)
);
CREATE INDEX idx_reputation_expires ON reputation (expires_at);

CREATE TABLE ioc (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ioc_type    VARCHAR(8)   NOT NULL,
    ioc_value   VARCHAR(253) NOT NULL,
    label       VARCHAR(200),
    source      VARCHAR(200),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ioc UNIQUE (ioc_type, ioc_value)
);

-- Group-IB (2025): O'zbekistonda tarqalgan SMS-o'g'ri va dropper namunalari
INSERT INTO ioc (ioc_type, ioc_value, label, source) VALUES
 ('SHA1', 'db1d14d5246f2c8807c55084b74247dea6465285', 'Wonderland (Sud Qarori.PDF (8).apk)', 'Group-IB 2025'),
 ('SHA1', '6f5502b0e2e99d5f9be4e5f9dcf3fa21b48a92e4', 'Wonderland', 'Group-IB 2025'),
 ('SHA1', '516943e93a2bd8f7d91dc5d8b130073d60f4fe67', 'Wonderland (Sud qarori)', 'Group-IB 2025'),
 ('SHA1', '6ab99f2396f309647f1adabd290f711960d41696', 'Wonderland (Siz bilan video)', 'Group-IB 2025'),
 ('SHA1', '3343e72eb3f04244c7ebf464883cb120365e3a4e', 'Wonderland (Toyga Taklifnoma)', 'Group-IB 2025'),
 ('SHA1', '916c66810f0c1ffb447ac98c8e707c75aa911b4f', 'MidnightDat (SUD CHAQIRUV)', 'Group-IB 2025'),
 ('SHA1', '85605b32c2a61c258709a19a54cb8a2aa59f8f04', 'MidnightDat (Toy Video Albom)', 'Group-IB 2025'),
 ('SHA1', '23cb06e1d97b951b36b77b0e7c38ccedb1f9ea2d', 'MidnightDat (Toy Video Albom)', 'Group-IB 2025'),
 ('SHA1', 'e2ca86efebc6338a37cdcc0f07ea5d1e8eeeb53a', 'MidnightDat', 'Group-IB 2025'),
 ('SHA1', '2dd2371efced160743d88ef08905e3eb7aa83531', 'MidnightDat (SudIlovasi)', 'Group-IB 2025'),
 ('SHA1', 'c8b8415ee68ec26af544d2ec9d5b8e86e6670690', 'RoundRift (toydan video)', 'Group-IB 2025'),
 ('SHA1', 'd5b1e45cdf941e5e5771b50881e167dea8020b18', 'RoundRift (To''ydan video)', 'Group-IB 2025'),
 ('SHA1', '86ee96cd11cf08f37a511fa860c78b12cb237b73', 'RoundRift (Kamera yozuvi)', 'Group-IB 2025'),
 ('SHA1', '22b7bc9bdccbdac0ec40cf8cedaf7bce3b313e94', 'RoundRift (to''ydan video)', 'Group-IB 2025'),
 ('SHA1', '9374204e405814cd2a0f364272cf1b417a9b0163', 'RoundRift (to''ydan video)', 'Group-IB 2025');
